version: '3.8'

services:
  backend:
    build: ./adrift
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./adrift/:/usr/src/adrift/
      - ./adrift/logs/:/usr/src/adrift/logs/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432

  zookeeper:
    image: wurstmeister/zookeeper
    env_file:
      - ./.env.dev
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    env_file:
      - ./.env.dev
    volumes:
      # docker socket which mounted to communicate with other services in docker (it's to manage topics and what not)
      - docker_sock:/var/run/docker.sock

volumes:
  postgres_data:
  docker_sock: