# Generated by Django 5.0.6 on 2024-06-22 10:00

from django.db import migrations, models
from bookings.enums import BookingType


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('CHILD', 'Child'), ('ADULT', 'Adult'), ('DISABLED', 'Disabled')], default=BookingType.ADULT, max_length=30),
            preserve_default=False,
        ),
    ]
