# Generated by Django 5.0.6 on 2024-06-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
    ]
