# Generated by Django 5.0.6 on 2024-06-22 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address'),
        ('movies', '0004_rename_language_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='place_of_birth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='core.address'),
        ),
        migrations.DeleteModel(
            name='PersonAddress',
        ),
    ]
