# Generated by Django 5.0.6 on 2024-06-22 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address'),
        ('theaters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='core.address'),
        ),
        migrations.DeleteModel(
            name='TheaterAddress',
        ),
    ]
